### PR TITLE
Only upload images to Percy from latest Julia version

### PR DESCRIPTION
**Pull request by hannahilea**
...by only uploading results from Julia v1.

- [x] Merge block: confirm percy upload actually happens!

### CODE REVIEW

**Review by kimlaberinto — APPROVED** [review]
Ah, I see what is going on. This PR adds the `if` line to the percy action so that only the latest version of Julia uploads images to Percy.

More context here on why we needed this: https://github.com/beacon-biosignals/Lighthouse.jl/pull/90#issuecomment-1279132746

LGTM

**Comment by kimlaberinto** [comment]
(I didn't check Percy yet, checks still happening) Also I modified the PR title, but feel free to wordsmith/change it some more

**Comment by hannahilea** [comment]
Previously they'd all upload their results---so whether we passed the percy test depended on the last CI run (aka the last julia version) to upload results. Now, we'll always be checking against the most recent release of julia. 

We therefore (previously-except-by-race and still) will not check if older versions regress---if that seems worth it, we can update the percy image paths to be prefixed with julia version so that they can all be uploaded separately. I think that might be overkill for how this package is currently being used, and the fact that we already have Percy upload amount limitations that we're up against? But I could be convinced otherwise!

**Comment by kimlaberinto** [comment]
Agree'd! I think this was a good choice to just note down visual changes from latest Julia version

**Pull request merged**
