### PR TITLE
bump Makie compat

### PR DESCRIPTION
**Pull request by ericphanson**

### CODE REVIEW

**Comment by palday** [comment]
docs build is erroring because Makie no longer ignores invalid kwargs. I haven't looked more closely yet but I suspect we're just forwarding all kwargs to all plots even when some kwargs only apply to some plots.

**Comment by ericphanson** [comment]
`Invalid attribute makersize` 🙃

**Comment by palday** [comment]
now `markerstrokewidth` 😞

**Review by palday — APPROVED** [review]
thanks!

**Pull request merged**
