### PR TITLE
update to new Makie version

### PR DESCRIPTION
**Pull request by SimonDanisch**
Need to drop < 0.15.2, because of the alias changes for Point/RGBA

### CODE REVIEW

**Comment by SimonDanisch** [comment]
Should this change prevent merging?
From:
image
To:
image

I will be able to fix it with:
https://github.com/JuliaPlots/Makie.jl/pull/1649
But would need to wait for a release...

**Review by hannahilea — CHANGES_REQUESTED** [review]
Ping me again once that Makie update happens and we'll get this merged in! :)

**Comment by SimonDanisch** [comment]
Hm, I guess there is still something like 0.5-1pixel offset, turning up in the percy diffs...

**Comment by SimonDanisch** [comment]
@hannahilea I don't think I'll be able to fix the 0.5pixel offset with reasonable effort, so I think we'll need to merge it like this ;)

**Review by hannahilea — APPROVED** [review]
Sounds good!

**Pull request merged**
