### PR TITLE
upgrade to Makie v0.18

### PR DESCRIPTION
**Pull request by SimonDanisch**
The new stricter checking for attributes uncovered a spelling mistake in the theme, but besides looks like the upgrade works fine.

### CODE REVIEW

**Review by hannahilea — APPROVED** [review]

**Comment by SimonDanisch** [comment]
I think the Percy diffs run into the issue of not really comparing to an older baseline since we haven't run percy in a long time?
The output looks fine too me, but could someone look over it again as well?

**Comment by hannahilea** [comment]
I don't see any percy diffs? Unless someone has already approved them so they aren't showing up...

**Comment by hannahilea** [comment]
My guess is that we have a percy race condition, where 1.6 and 1.7 generate different images, so if 1.6 had posted results and 1.7 hadn't, there could have been diffs until 1.7 posted. I'll fix that race condition in a follow-up PR; for now, no percy diffs so okay to merge, I think.

**Comment by hannahilea** [comment]
ah, the version didn't get bumped here, so we can't tag a release. opening a follow-up pr.

**Pull request merged**
